# this returns the number of representatives per party, and the total number of voters(and abstainers) at the time of a given bill.

select distinct ?bill ?party (COUNT(distinct ?voter_1) as ?num_party_members) (COUNT(distinct ?voter_2) as ?num_voters)
where {
	?voter_1 votes:votesOn ?bill.
    ?voter_1 dbo:party ?party.
	?voter_2 votes:votesOn ?bill.
}
group by ?bill ?party
order by desc(?num_party_members)
