
select ?voting_assembly ?bill (?date as ?date) ?party (abs(?yes_members-?no_members)/?total_voting_members as ?difference)
where {
    select distinct ?voting_assembly ?bill ?party (count(distinct ?voter_1) as ?yes_members) (count(distinct ?voter_2) as ?no_members) ?date ((?voter_1 + ?voter_2) as ?total_voting_members)
    where {
        ?voter_1 votes:votesOn ?bill.
        ?voter_1 dbo:party ?party.
        ?voter_2 dbo:party ?party.
        ?voter_2 votes:upvotes ?bill.
        ?voter_2 votes:downvotes ?bill.
        ?bill votes:processedBy ?voting_assembly.
        ?bill xsd:date ?date.
    }
    group by ?bill ?party ?party_members ?voters ?date ?voting_assembly
}
order by desc (?difference)