
select ?voting_assembly ?bill (?date as ?bill_date) ?party (?party_members/?voters as ?proportion)
where {
    select distinct ?voting_assembly ?bill ?party (count(distinct ?voter_1) as ?party_members) (count(distinct ?voter_2) as ?voters) ?date
    where {
        ?voter_1 votes:votesOn ?bill.
        ?voter_1 dbo:party ?party.
        ?voter_2 votes:votesOn ?bill.
        ?bill votes:processedBy ?voting_assembly.
        ?bill xsd:date ?date.
    }
    group by ?bill ?party ?party_members ?voters ?date ?voting_assembly
}
order by desc (?party_members/?voters)