

  select distinct

        # target values
        ?assembly
        ?bill
        ?bill_date
        ?bill_text
        ?party
        ?yes_members
        ?no_members
        ?abstain_members

        # the degree of uniformity, by some measure. is 0 if 50/50, is 1 if all voted in same direction
        ((abs(?yes_members-?no_members)/(?yes_members+?no_members)) as ?uniformity)
        ((?abstain_members/(?yes_members + ?no_members + ?abstain_members)) as ?abstain_proportion)
  #      ((?yes_members + ?no_members + ?abstain_members) / ?voters as ?party_rep_proportion )

  where {

      select distinct

            # target values
            ?assembly
            ?bill
            ?bill_date
            ?bill_text
            ?party

            # the number of voters who voted for the target bill
            # to heavy # (count(?voter_4) as ?voters)

            # the number of members of the target party who voted in each direction
            (count(distinct ?voter_1) as ?yes_members)
            (count(distinct ?voter_2) as ?no_members)
            (count(distinct ?voter_3) as ?abstain_members)

      where {

            # we only consider bills of the target assembly
            ?bill votes:processedBy ?assembly.

            # the date of the bill's voting event
            ?bill xsd:date ?bill_date.

            # the bill's text
            ?bill votes:bill_text ?bill_text.

            # we only consider voters that are member of the target party
            ?voter_1 dbo:party ?party.
            ?voter_2 dbo:party ?party.
            ?voter_3 dbo:party ?party.

            # we identify upvoters, downvoters, and abstainers
            ?voter_1 votes:upvotes ?bill.
            ?voter_2 votes:downvotes ?bill.
            ?voter_3 votes:abstains ?bill.

            # any voter that voted for this bill
            # too heavy # ?voter_4 votes:votesOn ?bill.

      }
      group by ?bill ?party ?party_members ?assembly ?bill_date ?bill_text # ?voters
  }
  group by ?assembly ?party ?bill ?yes_members ?no_members ?abstain_members ?bill_date ?bill_text # ?voters
